services:
  - type: web
    name: notes-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://notes-backend-awu3.onrender.com
